name: slack-approval
description: Custom action to send approval request to Slack from GitHub Actions
author: varu3

branding:
  icon: plus
  color: green

runs:
  using: node20
  main: dist/index.js
