name: slack-approval
description: Custom action to send approval request to Slack from GitHub Actions
author: Takashicc

inputs:
  bot-token:
    description: "Slack bot token"
    required: true
  app-token:
    description: "Slack app token"
    required: true
  channel-id:
    description: "Slack channel ID"
    required: true
  mention-to-users:
    description: "Slack user IDs to mention"
    required: false
  mention-to-groups:
    description: "Slack group IDs to mention"
    required: false
  authorized-users:
    description: "Slack user IDs who are authorized to approve or reject"
    required: false
  authorized-groups:
    description: "Slack group IDs who are authorized to approve or reject"
    required: false

branding:
  icon: plus
  color: green

runs:
  using: "docker"
  image: "docker://ghcr.io/takashicc/slack-approval:2.0.2"
