name: tagpr

on:
  push:
    branches:
      - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - id: app-token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ steps.app-token.outputs.token }}

      - id: tagpr
        uses: Songmu/tagpr@5f88955ce2b34f19868a8c9cbe3baf6b73176f7b # v1
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
